aica-technology/modulo

source/modulo_components/include/modulo_components/ComponentInterface.hpp

- #27 
Small fix. Components are allowed to have a namespace, so using just the name is potentially ambiguous; if you have components `/bar/foo` and `/baz/foo`, they would overlap with the name `foo`.
Estimated Time of Review: 0.1 minutes

Write the fully qualified node name in the predicate message

---

source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/test/cpp/test_component_communication.cpp
source/modulo_components/test/cpp/test_lifecycle_component_communication.cpp
source/modulo_components/test/python/test_component_communication.py
source/modulo_components/test/python/test_lifecycle_component_communication.py

- #27 
`get_fully_qualified_name()` is not correct for the lifecycle component, so this needs specialization until we refactor the component interface.

Specialize templates to get fully qualified name

---

.github/workflows/generate-docs.yml
CHANGELOG.md
README.md

This PR fixes a few links in the README and simplifies the generate docs workflow. Nothing fancy.

chore: fix links in readme

---

CHANGELOG.md
source/modulo_interfaces/CMakeLists.txt
source/modulo_interfaces/README.md
source/modulo_interfaces/msg/Predicate.msg
source/modulo_interfaces/msg/PredicateCollection.msg
source/modulo_interfaces/package.xml
source/modulo_interfaces/srv/EmptyTrigger.srv
source/modulo_interfaces/srv/StringTrigger.srv

- #73 
This PR solves the issue by adding a new package `modulo_interfaces` which comes with an updated message definition of the predicate message that contains `controller` and `hardware` in addition.

feat: add modulo interface package

---

.github/workflows/build-release.yaml

As title suggests
Estimated Time of Review: 1.1 minutes
- [ n/a] Confirm that the relevant changelog(s) are up-to-date in case of any user-facing changes

ci: use more powerful arm runner for build

---

.devcontainer/devcontainer.json
CHANGELOG.md
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/src/ComponentInterface.cpp

This reverts commit 59b4b6effd2ab5f7e24b1a8c4e359442871538b9.
This commit breaks modulo, so we need to put it off until 5.0.0. I will reopen the issue #67  to not forget.
- #80

Revert "feat: add mutex around step callback (#69)"

---

CHANGELOG.md
source/modulo_core/include/modulo_core/translators/message_readers.hpp
source/modulo_core/src/translators/parameter_translators.cpp

- #65 
This PR solves the issue by using the new function from state representation to give a more verbose error message in the translators

feat: improve logging in parameter translators

---

CHANGELOG.md
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/test/python/conftest.py
source/modulo_components/test/python/test_component_communication.py
source/modulo_components/test/python/test_lifecycle_component_communication.py

- #71 
This PR solves the issue by checking that the received message can be cast to the existing object type

fix(component-interface): make python subscriptions type safe

---

.vscode/settings.json
CHANGELOG.md
Dockerfile
build.sh

The first step towards public modulo controller interfaces

build: use new ros2 workspace base image

---

CHANGELOG.md
source/modulo_core/include/modulo_core/translators/message_readers.hpp

- #77 
Another small breaking change that we already had planned

refactor: rename function in modulo translators

---

.devcontainer/devcontainer.json
CHANGELOG.md
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/src/ComponentInterface.cpp

This reverts commit 486ab2d8ce13194067eef2fb0d425aed5b7f177d.
- #67 
I'm starting a branch that contains breaking changes, so this commit can go back in

Revert "Revert "feat: add mutex around step callback (#69)""

---

CHANGELOG.md
source/modulo_controllers/include/modulo_controllers/ControllerInterface.hpp
source/modulo_controllers/src/ControllerInterface.cpp

Small bug that was found today

fix: correctly call on_deactivate wrapper

---

CHANGELOG.md
source/modulo_controllers/controller_descriptions/modulo_controllers_controller_interface.json
source/modulo_controllers/controller_descriptions/modulo_controllers_robot_controller_interface.json
source/modulo_controllers/src/RobotControllerInterface.cpp

Porting this from https://github.com/aica-technology/modulo-controllers/pull/215

fix: decay previous command correctly

---

CHANGELOG.md
source/modulo_controllers/src/RobotControllerInterface.cpp

Porting from https://github.com/aica-technology/modulo-controllers/pull/216/

fix: move command interface setting into correct conditional blocks

---

CHANGELOG.md
source/modulo_controllers/include/modulo_controllers/ControllerInterface.hpp
source/modulo_controllers/src/ControllerInterface.cpp

- https://github.com/aica-technology/modulo-controllers/pull/194
Since the PR in modulo controllers for this feature is breaking and I don't expect a new major version in modulo controllers with the controller interface, we can deal with this here in a non breaking fashion. This PR resolves some TODOs regarding signal name validation in a similar way to modulo components.

feat(controller-interface): validate signal names

---

.github/workflows/build-release.yaml
.github/workflows/test.yml
CHANGELOG.md
Dockerfile
README.md
aica-package.toml
source/modulo_core/CMakeLists.txt

- #91
This PR approaches the issue by defining modulo as a collection of packages with package-builder:v1. It doesn't yet make any changes to the CI to build from aica-package.toml.
- https://github.com/aica-technology/docker-images/pull/109
(the current metadata for `ros2-ws:v1.0.0-iron` is invalid for package-builder:v1)

build: aica-package.toml for package-builder:v1

---

CHANGELOG.md
source/modulo_controllers/include/modulo_controllers/ControllerInterface.hpp
source/modulo_controllers/include/modulo_controllers/RobotControllerInterface.hpp
source/modulo_controllers/src/ControllerInterface.cpp
source/modulo_controllers/src/RobotControllerInterface.cpp

- #102 
PR into breaking branch. Adding `add_interfaces` for derived controllers according to parent issue.

feat: add add_interfaces function for derived controllers

---

CHANGELOG.md
source/modulo_controllers/README.md

Forgot to copy paste some of the readme when I moved the controller interfaces here.

feat(modulo-controller): add missing docs

---

CHANGELOG.md
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/src/Component.cpp
source/modulo_components/src/ComponentInterface.cpp
source/modulo_components/src/LifecycleComponent.cpp
source/modulo_components/test/cpp/test_component.cpp
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/cpp/test_lifecycle_component.cpp
source/modulo_components/test/python/test_component.py
source/modulo_components/test/python/test_component_interface.py
source/modulo_components/test/python/test_lifecycle_component.py
source/modulo_controllers/src/ControllerInterface.cpp
source/modulo_utils/include/modulo_utils/parsing.hpp
source/modulo_utils/modulo_utils/parsing.py

- #101 
This PR solves the issue by adding the warning to the parsing utilities

feat: define topic validation warning in utilities

---

.vscode/c_cpp_properties.json
CHANGELOG.md
aica-package.toml
source/modulo_components/src/Component.cpp
source/modulo_components/src/LifecycleComponent.cpp
source/modulo_components/test/cpp/include/test_modulo_components/component_public_interfaces.hpp
source/modulo_controllers/CMakeLists.txt
source/modulo_controllers/test/test_controller_interface.cpp
source/modulo_core/CMakeLists.txt
source/modulo_core/test/cpp/communication/test_communication.cpp

No going back now...
Only minor updates were required.

feat: update to jazzy and CL v9.0.0

---

CHANGELOG.md
source/modulo_controllers/src/ControllerInterface.cpp

Another breaking change. The predicates of controllers should be published onto the same topic as component predicates now since they have the same message type. 
Next step: Only publish predicates on change!

refactor: change predicate topic of controllers

---

.github/workflows/build-release.yaml
aica-package.toml

The CI in #127 had a tiny mistake, which resulted in the image not being tagged with `v5.0.0-rc0001`. This should now be fixed and the CI should push a `v5.0.0-rc0002` after this PR

ci: fix check version workflow

---

.github/workflows/build-release.yaml
aica-package.toml

If only I would pay attention to details sometimes...

ci: fix image tags

---

aica-package.toml

Quick update to the rc2 base image

release: version 5.0.0-rc0005

---

source/modulo_core/include/modulo_core/communication/MessagePair.hpp
source/modulo_core/include/modulo_core/communication/PublisherHandler.hpp
source/modulo_core/include/modulo_core/concepts.hpp
source/modulo_core/test/cpp/communication/test_message_pair.cpp
source/modulo_core/test/cpp/communication/test_publisher_handler.cpp

Name revision to the concepts as well as the addition of the PrimitiveMsgT that is required for the handlers as well.

feat: revise concepts

---

source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_core/include/modulo_core/communication/PublisherHandler.hpp
source/modulo_core/include/modulo_core/communication/SubscriptionHandler.hpp

This PR allows to pass down a logger to the subscription handler such that it can use the logger from the node.

feat: add optional logger to subscription handler

---

.vscode/c_cpp_properties.json
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/src/ComponentInterface.cpp
source/modulo_components/test/python/conftest.py
source/modulo_components/test/python/test_component.py
source/modulo_components/test/python/test_component_communication.py
source/modulo_components/test/python/test_component_interface.py
source/modulo_components/test/python/test_lifecycle_component.py

feat: enable custom signal types in Python

---

source/modulo_components/include/modulo_components/LifecycleComponent.hpp
source/modulo_components/src/LifecycleComponent.cpp

As you suggested, works well :+1:
Estimated Time of Review: 4 minutes

feat: optimize creation and configuration of lifecycle publishers

---

CHANGELOG.md
source/modulo_components/component_descriptions/modulo_component.json
source/modulo_components/component_descriptions/modulo_lifecycle_component.json

Small correction
Estimated Time of Review: 1.1 minutes

docs: update schema path in component descriptions

---

CHANGELOG.md
aica-package.toml
source/modulo_components/package.xml
source/modulo_controllers/package.xml
source/modulo_core/package.xml
source/modulo_utils/package.xml

:bullettrain_side: 
Estimated Time of Review: 4 minutes

release: version 5.0.1

---

CHANGELOG.md
source/modulo_controllers/src/BaseControllerInterface.cpp

fix(controllers): trigger check

---

aica-package.toml

release: version 5.1.0-rc0001

---

CHANGELOG.md
source/modulo_components/test/python/conftest.py
source/modulo_components/test/python/test_lifecycle_component_communication.py
source/modulo_controllers/package.xml

Just a minor change here, realized that there was a test case missing for the lifecycle component

fix(components): add missing test case

---

CHANGELOG.md
source/modulo_components/src/ComponentInterface.cpp
source/modulo_controllers/include/modulo_controllers/BaseControllerInterface.hpp
source/modulo_controllers/src/BaseControllerInterface.cpp
source/modulo_controllers/test/test_controller_interface.cpp

Since this is unfortunately ABI breaking, let's take it out and bring it back with the next major release. Sorry about that. I will fast forward the commits without squashing

Revert TF listener and broadcaster feature

---

CHANGELOG.md
source/modulo_components/src/ComponentInterface.cpp
source/modulo_controllers/include/modulo_controllers/BaseControllerInterface.hpp
source/modulo_controllers/src/BaseControllerInterface.cpp
source/modulo_controllers/test/test_controller_interface.cpp

We can bring those commits back on the breaking branch

Reapply TF features in modulo controllers

---

CHANGELOG.md
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/src/ComponentInterface.cpp
source/modulo_components/test/cpp/test_component_communication.cpp

Made a mistake with #189, need to do this again...

feat(components): use parent node for tf listener (cpp)

---

CHANGELOG.md
source/modulo_core/include/modulo_core/communication/MessagePair.hpp
source/modulo_core/include/modulo_core/communication/PublisherHandler.hpp
source/modulo_core/include/modulo_core/communication/SubscriptionHandler.hpp
source/modulo_core/test/cpp/communication/test_communication.cpp
source/modulo_core/test/cpp/communication/test_message_pair.cpp
source/modulo_core/test/cpp/communication/test_publisher_handler.cpp
source/modulo_core/test/cpp/communication/test_subscription_handler.cpp

- #199 
This PR solves the issue by adding additional logic to cover rarer cases where generic inputs/outputs will fall into conditions that do not trigger exceptions and thus fail silently.

fix: handle custom message pub/sub that also exist in translators

---

CHANGELOG.md
source/modulo_core/modulo_core/__init__.py
source/modulo_core/modulo_core/exceptions.py
source/modulo_core/modulo_core/joint_positions_broadcaster.py
source/modulo_core/modulo_core/joint_positions_listener.py
source/modulo_core/test/python/conftest.py
source/modulo_core/test/python/test_joint_positions.py

- #196
This PR adds the joint positions broadcaster and listener in python too.

feat(core): add joint positions broadcaster and listener (py)

---

CHANGELOG.md
source/modulo_core/CMakeLists.txt
source/modulo_core/include/modulo_core/JointPositionsBroadcaster.hpp
source/modulo_core/include/modulo_core/JointPositionsListener.hpp
source/modulo_core/include/modulo_core/exceptions.hpp
source/modulo_core/include/modulo_core/joint_positions_options.hpp
source/modulo_core/modulo_core/__init__.py
source/modulo_core/modulo_core/exceptions.py
source/modulo_core/modulo_core/joint_positions_broadcaster.py
source/modulo_core/modulo_core/joint_positions_listener.py
source/modulo_core/src/JointPositionsBroadcaster.cpp
source/modulo_core/src/JointPositionsListener.cpp
source/modulo_core/test/cpp/test_joint_positions.cpp
source/modulo_core/test/python/conftest.py
source/modulo_core/test/python/test_joint_positions.py
source/modulo_interfaces/CMakeLists.txt
source/modulo_interfaces/README.md
source/modulo_interfaces/msg/JointPositions.msg
source/modulo_interfaces/msg/JointPositionsCollection.msg
source/modulo_interfaces/package.xml

- #196 
Fast forwarding the commits from the staging branch to main

feat: joint positions

---

CHANGELOG.md
aica-package.toml
source/modulo_components/package.xml
source/modulo_controllers/package.xml
source/modulo_core/package.xml
source/modulo_interfaces/package.xml
source/modulo_utils/package.xml

:bullettrain_side: 
Release time

release: version 5.2.0

---

CHANGELOG.md
source/modulo_controllers/controller_descriptions/modulo_controllers_base_controller_interface.json
source/modulo_controllers/controller_descriptions/modulo_controllers_controller_interface.json
source/modulo_controllers/src/BaseControllerInterface.cpp
source/modulo_controllers/src/ControllerInterface.cpp

fix(controllers): move input validity period to base

---

CHANGELOG.md
source/modulo_controllers/include/modulo_controllers/BaseControllerInterface.hpp
source/modulo_controllers/include/modulo_controllers/ControllerInterface.hpp
source/modulo_controllers/src/BaseControllerInterface.cpp
source/modulo_controllers/src/ControllerInterface.cpp
source/modulo_controllers/src/RobotControllerInterface.cpp

- related to #207
This PR removes the unnecessary setter and correctly validates the activation timeout in the `ControllerInterface`

fix(controllers)!: remove input validity setter

---

CHANGELOG.md
aica-package.toml
source/modulo_components/package.xml
source/modulo_controllers/package.xml
source/modulo_core/package.xml
source/modulo_utils/package.xml

release: version 5.2.1

---

CHANGELOG.md
aica-package.toml
source/modulo_components/package.xml
source/modulo_controllers/package.xml
source/modulo_core/package.xml
source/modulo_utils/package.xml

:steam_locomotive: 
lets get rolling

release: version 5.2.2
