CHANGELOG.md
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/src/ComponentInterface.cpp

This PR finally solves the problem with unloading components after the component interface refactor. It's been some time since we last worked on this but I rebased the 'iron' branch (the branch that has the 4 commits regarding the component interface refactor with node interfaces) and found that the issue with that was just an additional callback group that I created for I don't know what reason and that group was responsible for the issues when removing the component from the executor.

Remove callback group for topics and services

---

CHANGELOG.md
source/modulo_components/CMakeLists.txt
source/modulo_components/include/modulo_components/Component.hpp
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/include/modulo_components/LifecycleComponent.hpp
source/modulo_components/src/Component.cpp
source/modulo_components/src/ComponentInterface.cpp
source/modulo_components/src/LifecycleComponent.cpp
source/modulo_components/test/cpp/include/test_modulo_components/component_public_interfaces.hpp
source/modulo_components/test/cpp/test_component.cpp
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/cpp/test_component_interface_empty_parameters.cpp
source/modulo_components/test/cpp/test_component_interface_parameters.cpp
source/modulo_components/test/cpp/test_lifecycle_component.cpp

- #32 
These 5 PRs have been reviewed independently and the latest commit has been tested to some extent already. How should we proceed here? Should I change the commit titles for each commit and then we fast forward those to main and test it as rolling?
I believe that this should then be modulo 4.0.0 as we have to rebuild all dynamic components with that version.

Refactor component interface using node interfaces

---

.github/workflows/build-release.yaml
CHANGELOG.md
source/modulo_components/test/cpp/test_component_interface.cpp

Before proceeding with the release, I realized that some tests were commented out so they can be removed because I moved them to another place.
Estimated Time of Review: 1.1 minutes

chore: remove unnecessary tests

---

.devcontainer/devcontainer.json
CHANGELOG.md
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/src/ComponentInterface.cpp

- #67 
This PR solves the issue by adding the mutex as proposed in the parent issue.
Would it be sensible to add the same thing in the python component interface?

feat: add mutex around step callback

---

CHANGELOG.md
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/include/modulo_components/utilities/utilities.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/modulo_components/utilities/utilities.py
source/modulo_components/src/ComponentInterface.cpp
source/modulo_components/test/cpp/test_component.cpp
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/cpp/test_lifecycle_component.cpp
source/modulo_components/test/python/test_component.py
source/modulo_components/test/python/test_component_interface.py
source/modulo_components/test/python/test_lifecycle_component.py

- #66 
This PR solves the issue by implementing the two first steps here in modulo. PR for docs will be in API

feat: add warn log when topics are sanitized

---

.devcontainer/devcontainer.json
CHANGELOG.md
Dockerfile
build.sh
source/modulo_core/CMakeLists.txt
source/modulo_core/include/modulo_core/translators/message_readers.hpp
source/modulo_core/test/cpp/communication/test_encoded_communication.cpp

- #70 
As title suggests. The one necessary change was to update a switch case in the message readers.

feat: support io states in modulo core

---

CHANGELOG.md
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/include/modulo_components/utilities/utilities.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/modulo_components/utilities/__init__.py
source/modulo_components/modulo_components/utilities/utilities.py
source/modulo_components/src/Component.cpp
source/modulo_components/src/ComponentInterface.cpp
source/modulo_components/src/LifecycleComponent.cpp
source/modulo_utils/include/modulo_utils/parsing.hpp
source/modulo_utils/include/modulo_utils/predicate_variant.hpp
source/modulo_utils/modulo_utils/parsing.py

Since the code form the predicate variant and other utilities is currently duplicated between modulo components and controllers, it's reasonable to move that to the utils package.

refactor: move utilities to modulo_utils package

---

CHANGELOG.md
source/modulo_controllers/include/modulo_controllers/ControllerInterface.hpp
source/modulo_controllers/src/ControllerInterface.cpp
source/modulo_controllers/src/RobotControllerInterface.cpp

- #82 
I'm working on harmonizing the provided interface between the component and controller classes. Hence the addition of `set_parameter_value`. Additionally I changed two things under the hood:
1. The validation of the base class parameters should not be the responsibility of the derived class. That's why - as in the component interface - the `on_validate_parameter_callback` is wrapped in an additional `validate_parameter` method
2. Two functions were inlined for no reason, I moved them to the source file.
Estimated Time of Review: 7 minutes

feat(controller-interface): add set_parameter_value

---

CHANGELOG.md
source/modulo_controllers/include/modulo_controllers/ControllerInterface.hpp
source/modulo_controllers/src/ControllerInterface.cpp

This is something that has bothered me a little bit for a while. If you check the modulo_controllers::ControllerInterface, you can see that all `on_XXX` transition callbacks are overridden, except the `on_init`. We chose to override that to assure that the base class `on_XXX` steps are always called, i.e. to not put the responsibility of putting `return ControllerInterface::on_XXX` into the derived class' callback onto the user.
However, this doesn't work with the `on_init` callback since it already has no arguments in the ros2 control base class. Meaning we now have mixed behavior where a derived class has to call the `on_init` of the parent explicitly, but not the other callbacks. One way that I can think of to remedy that is to check that the `on_init` has been called with a flag in …

feat: check that init of base class has been called

---

CHANGELOG.md
source/modulo_controllers/src/ControllerInterface.cpp

fix(modulo-controllers): improve log message

---

CHANGELOG.md
source/modulo_components/src/Component.cpp
source/modulo_components/src/LifecycleComponent.cpp

fix(modulo-components): add missing space in log message

---

CHANGELOG.md
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/src/ComponentInterface.cpp
source/modulo_components/test/cpp/test_component_interface_empty_parameters.cpp
source/modulo_components/test/cpp/test_component_interface_parameters.cpp
source/modulo_components/test/python/test_component_interface_empty_parameters.py

- #100
This PR solves the parent issue by adding a `pre_set_parameters_callback` to the component interfaces. Because the parametres in that feedback are mutable, we can basically run the whole validation in this callback, and just forward the result to the `on_set_parameters_callback`. 
It required some other changes that are rather hard to describe because of the somewhat complex call sequence in ROS but I'm happy to discuss any open points.
If you like it, I have to do the same in the modulo controllers.
Estimated Time of Review: 15 minutes

fix(components): keep parameter values in sync with ros

---

CHANGELOG.md
source/modulo_controllers/include/modulo_controllers/ControllerInterface.hpp

The original intention for this branch/PR was to investigate seg faults that would occur when running apps. Along with some issues in the way I was packaging (unrelated to this PR, but related to the seg faults I was seeing), we found a small issue in the way a failed dynamic_pointer_cast would be handled (i.e., it doesn't throw an exception, but returns nullptr).
There also seems to be some sort of issue where we get an EncodedState exception that is followed by a segmentation fault. I can't quite see a reason. We moved the second dereference of the message from `readFromNonRT` to potentially prevent this issue (in the case of some sync problem between first and second dereference). Despite this not being very likely, and also not being fully safe, it doesn't hurt to do this in one line. …

fix(modulo-controllers): correctly handle nullptr

---

CHANGELOG.md
source/modulo_controllers/include/modulo_controllers/RobotControllerInterface.hpp
source/modulo_controllers/src/RobotControllerInterface.cpp

- https://github.com/aica-technology/modulo-controllers/issues/195
This PR adds an argument to the class constructor that will load the geometry features for the robot model. 

feat: add flag for collision features to robot controller interface

---

CHANGELOG.md
source/modulo_components/include/modulo_components/Component.hpp
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/include/modulo_components/LifecycleComponent.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/src/ComponentInterface.cpp
source/modulo_components/test/cpp/include/test_modulo_components/component_public_interfaces.hpp
source/modulo_components/test/cpp/test_component_communication.cpp
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/cpp/test_lifecycle_component_communication.cpp
source/modulo_components/test/python/test_component_communication.py
source/modulo_components/test/python/test_component_interface.py
source/modulo_components/test/python/test_lifecycle_component_communication.py
source/modulo_core/include/modulo_core/Predicate.hpp
source/modulo_core/modulo_core/__init__.py
source/modulo_core/modulo_core/predicate.py
source/modulo_core/test/cpp/test_predicate.cpp

- #122 
This PR solves the issue by implementing option 3 of the parent issue. Review by commit (there was an intermediate commit just for formatting).
Estimated Time of Review: 15 minutes

feat(components): only publish predicates on value change

---

CHANGELOG.md
build.sh
source/modulo_controllers/CMakeLists.txt
source/modulo_controllers/include/modulo_controllers/ControllerInterface.hpp
source/modulo_controllers/src/ControllerInterface.cpp
source/modulo_controllers/test/test_controller_interface.cpp

#100
This PR solves the issue by applying the same changes as in #111 to the controller interface.

fix(controllers): keep parameter values in sync with ros

---

CHANGELOG.md
source/modulo_components/component_descriptions/modulo_component.json
source/modulo_components/component_descriptions/modulo_lifecycle_component.json

Following aica-technology/api#168, this uses the new 1-1-1 component description schema to set the lifecycle property to true for the lifecycle component description.

feat(components): use component description schema 1-1-1 to mark lifecycle property

---

CHANGELOG.md
aica-package.toml

release: use updated base image

---

CHANGELOG.md
aica-package.toml
source/modulo_controllers/include/modulo_controllers/BaseControllerInterface.hpp
source/modulo_controllers/src/BaseControllerInterface.cpp

The `get_lifecycle_state` function is now already defined in the controller interface since [this commit](https://github.com/ros-controls/ros2_control/pull/1683). No need to define it again ourselves.

fix(controllers): remove duplicate function

---

source/modulo_controllers/include/modulo_controllers/BaseControllerInterface.hpp
source/modulo_controllers/src/BaseControllerInterface.cpp
source/modulo_controllers/test/test_controller_interface.cpp

- #151 
This PR solves the issue by implementing compile-time logic to allow for custom types.

feat: support generic inputs for controllers

---

source/modulo_controllers/include/modulo_controllers/BaseControllerInterface.hpp
source/modulo_controllers/src/BaseControllerInterface.cpp
source/modulo_controllers/test/test_controller_interface.cpp
source/modulo_core/include/modulo_core/concepts.hpp

This PR adds support for generic outputs in controllers. Similarly to #145, we use compile-time data type inference to make sure that custom (ROS) types are 1) added to the output map generically, 2) are directly published when `write_output` is invoked.
- #151 

feat!: support generic inputs and outputs in controllers

---

CHANGELOG.md
aica-package.toml

For testing purposes
Estimated Time of Review: 0.5 minutes

release: version v5.0.0-rc0009

---

CHANGELOG.md
aica-package.toml
source/modulo_components/component_descriptions/modulo_lifecycle_component.json
source/modulo_components/include/modulo_components/Component.hpp
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/include/modulo_components/LifecycleComponent.hpp
source/modulo_components/modulo_components/component.py
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/modulo_components/lifecycle_component.py
source/modulo_components/src/Component.cpp
source/modulo_components/src/ComponentInterface.cpp
source/modulo_components/src/LifecycleComponent.cpp
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/python/test_component_interface.py
source/modulo_controllers/src/BaseControllerInterface.cpp

- #40 
I wouldn't say that this PR solves the parent issue but at least it removes a feature that is not fully supported, desired and thought through.

refactor(components): improve component error handling

---

CHANGELOG.md
aica-package.toml
source/modulo_components/include/modulo_components/Component.hpp
source/modulo_components/modulo_components/lifecycle_component.py
source/modulo_components/src/Component.cpp

Due to missing switch cases in Python we have to manually trigger everything correctly.
Estimated Time of Review: 4 minutes

fix(components): correctly go through shutdown sequence

---

CHANGELOG.md
aica-package.toml
doxygen/doxygen.conf
source/modulo_components/package.xml
source/modulo_controllers/package.xml
source/modulo_core/package.xml
source/modulo_utils/package.xml

IT'S TIME :fire: :bullettrain_side: 

release: version 5.0.0

---

CHANGELOG.md
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/test/cpp/include/test_modulo_components/communication_components.hpp
source/modulo_components/test/cpp/test_component_communication.cpp
source/modulo_components/test/cpp/test_lifecycle_component_communication.cpp
source/modulo_components/test/python/conftest.py
source/modulo_components/test/python/test_component_communication.py
source/modulo_components/test/python/test_lifecycle_component_communication.py
source/modulo_core/include/modulo_core/Predicate.hpp
source/modulo_core/modulo_core/predicate.py
source/modulo_core/test/cpp/test_predicate.cpp
source/modulo_core/test/python/test_predicate.py
source/modulo_utils/modulo_utils/testutils/predicates_listener.py
source/modulo_utils/test/python/test_encoded_state_recorder.py

- #158 
The original problem of the parent issue is solved in cc85c642f3e48c0e15f78a612cc81f40a1698170. However, as explained there is another problem which is that the initialization of the `previous_value` in the `Predicate` class is not ideal and should be revised.
Review by commit

fix: default predicate value on construction

---

CHANGELOG.md
source/modulo_controllers/controller_descriptions/modulo_controllers_controller_interface.json
source/modulo_controllers/src/BaseControllerInterface.cpp
source/modulo_controllers/src/ControllerInterface.cpp

This PR fixes a small inconsistency in the controller base class, where the rate was still an integer parameter and not a double. Since the parameter is marked internal, we don't have to worry about breaking applications or so because it was not exposed so far.

fix(controllers): change predicate rate to double type

---

CHANGELOG.md
source/modulo_components/modulo_components/component.py
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/modulo_components/lifecycle_component.py
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/python/test_component.py
source/modulo_components/test/python/test_component_communication.py
source/modulo_components/test/python/test_component_interface.py
source/modulo_components/test/python/test_lifecycle_component.py
source/modulo_components/test/python/test_lifecycle_component_communication.py

This PR improves the robustness of the Python component interfaces. It is possible that a user overwrites some of these attributes and completely breaks the components (for example `self._period = 0.0` already completely breaks a components).
In this PR I made all possible attributes of components "private" and the necessary "protected" ones a bit more verbose to minimize chances of overriding. Two main disadvantages:
1. the lifecycle component now also needs to keep track of outputs, its kind of a duplicated dict but the only way to avoid having  the `_outputs` "only protected"
2. A lot of the tests would have to disappear since they rely heavily on the fact that we can do stuff like `assert "test" in component._outputs.keys()`
What do you think? A valuable improvement or not?
Estimated …

fix(components): make all possible attributes private

---

CHANGELOG.md
aica-package.toml
source/modulo_components/package.xml
source/modulo_controllers/package.xml
source/modulo_core/package.xml
source/modulo_utils/package.xml

:train: 
This PR releases two fixes in modulo as 5.0.2.
We could also include #162 if we want.

release: version 5.0.2

---

CHANGELOG.md
source/modulo_components/modulo_components/lifecycle_component.py

Small problem introduced by me in #162.

fix(components): remove incorrect log line

---

CHANGELOG.md
source/modulo_controllers/controller_descriptions/modulo_controllers_base_controller_interface.json
source/modulo_controllers/controller_descriptions/modulo_controllers_controller_interface.json
source/modulo_controllers/src/BaseControllerInterface.cpp
source/modulo_controllers/src/ControllerInterface.cpp

- n/a
This PR solves the issue by moving the `add_parameter` upwards in the `BaseControllerInterface`.

fix: move predicate publishing rate parameter to base controller

---

CHANGELOG.md
source/modulo_components/src/ComponentInterface.cpp
source/modulo_controllers/include/modulo_controllers/BaseControllerInterface.hpp
source/modulo_controllers/src/BaseControllerInterface.cpp

- #169 
This PR solves the issue by replicating the TF listener functions from `ComponentInterface`.
Estimated Time of Review: 8 minutes

feat: add TF listener and lookup TF helpers in BaseControllerInterface

---

CHANGELOG.md
source/modulo_controllers/include/modulo_controllers/BaseControllerInterface.hpp
source/modulo_controllers/src/BaseControllerInterface.cpp

- #170 
This PR solves the issue by replicating the TF broadcaster functions introduced in `ComponentInterface`.
Estimated Time of Review: 8 minutes

feat: add TF broadcaster in BaseControllerInterface

---

source/modulo_controllers/include/modulo_controllers/BaseControllerInterface.hpp
source/modulo_controllers/src/BaseControllerInterface.cpp

fix: handle uninitialized node correctly

---

CHANGELOG.md
source/modulo_controllers/include/modulo_controllers/BaseControllerInterface.hpp
source/modulo_controllers/src/BaseControllerInterface.cpp
source/modulo_controllers/test/test_controller_interface.cpp

- n/a
This PR solves the issue by replicating the tests from the `ComponentInterface`.
- #169 
- #170 
- #171 
- #173

test(controllers): add TF listener and broadcaster tests

---

CHANGELOG.md
source/modulo_components/src/ComponentInterface.cpp
source/modulo_controllers/include/modulo_controllers/BaseControllerInterface.hpp
source/modulo_controllers/src/BaseControllerInterface.cpp
source/modulo_controllers/test/test_controller_interface.cpp

As described in #169 and #170, this PR adds helper functions to use TF listeners and broadcasters in controllers.
- n/a
This PR solves the issue by replicating the necessary functions as originally designed in `ComponentInterface`
Estimated Time of Review: 15 minutes
- #169 
- #170 
- #173 
- #171 
- #172

feat(controllers): add TF listener and broadcaster to controllers

---

CHANGELOG.md
source/modulo_components/modulo_components/component.py
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/modulo_components/lifecycle_component.py
source/modulo_components/test/python/conftest.py
source/modulo_core/modulo_core/translators/message_writers.py

One thing that has come to my attention with the recent documentation efforts and webinars is that the fact that we require the user to know the mapping between state representation type and the clproto message type when adding an output in python is a bit too much. I propose here in a non breaking fashion to remedy that by getting the clproto message type from the type of the class attribute. The functionality stays exactly the same (e.g. existing code still works and if a user wants to publish a CartesianPose as a CARTESIAN_STATE_MESSAGE, that is still possible), but for the simple case of the 1:1 mapping, the clproto message type is not required anymore to add an output.

feat(components): get clproto message type from attribute

---

CHANGELOG.md
source/modulo_components/modulo_components/lifecycle_component.py

Kind of a recurring issue that we had with clearing python components. From my tests this should not really remove the node from ROS (at least `ros2 node list` doesn't show the nodes anymore). Any other tests welcome.

fix(components): clean up lifecycle nodes properly

---

CHANGELOG.md
aica-package.toml
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/test/cpp/include/test_modulo_components/communication_components.hpp
source/modulo_components/test/cpp/test_component_communication.cpp
source/modulo_components/test/cpp/test_lifecycle_component_communication.cpp
source/modulo_components/test/python/conftest.py
source/modulo_components/test/python/test_component_communication.py
source/modulo_components/test/python/test_lifecycle_component_communication.py

This PR improves the robustness of the component interfaces by try catching subscription callbacks in all cases. Until now, we "only" try catched additional user callbacks.
One might argue that we should only catch `CoreException` and not all exceptions as the user might want to throw exceptions on purpose but I can not imagine a setup where one would desire to throw an exception in a subscription callback.
Also, we could put the component in error state by putting the `raise_error` there but that as well, I'm just not sure if I want to introduce it, since we'd have to do that consistently in all the `add_input` variants. I like the idea of subscription callbacks just failing with a throttled log instead of raising the error on the component.

fix(components): try catch subscription callbacks

---

CHANGELOG.md
aica-package.toml
source/modulo_components/package.xml
source/modulo_controllers/package.xml
source/modulo_core/package.xml
source/modulo_utils/package.xml

release: version 5.1.0

---

CHANGELOG.md
aica-package.toml
source/modulo_controllers/README.md
source/modulo_controllers/controller_descriptions/modulo_controllers_controller_interface.json
source/modulo_controllers/src/ControllerInterface.cpp
source/modulo_controllers/src/RobotControllerInterface.cpp

This PR removes the `robot_description` parameter of the controller interface because the robot description is already available through `get_robot_description()` of the ros2 control base class.
Breaking change and requires new base image, goes into staging branch

feat(controllers)!: remove robot description parameter

---

CHANGELOG.md
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/src/ComponentInterface.cpp
source/modulo_components/test/cpp/test_component_communication.cpp

- #187 
This PR solves the issue by passing in the parent node interfaces to avoid the creation of a separate node for the tf listener

feat(components): use parent node for tf listener (cpp)

---

CHANGELOG.md
source/modulo_controllers/src/BaseControllerInterface.cpp

Same as in #200. Goes to breaking branch

feat(controllers): use parent node for tf listener

---

CHANGELOG.md
source/modulo_components/modulo_components/component.py
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/modulo_components/lifecycle_component.py

- #205 
This PR modifies the component interfaces in Python in a way that there is a check for the return values of callbacks that are expected to be overridden. This allows better logging for the case where a user might forget to return a bool. Also, to close #205, I catch attribute errors on `validate_parameter` and log an error to help the user debug the component.

feat(components): verify return value of callbacks

---

CHANGELOG.md
aica-package.toml
source/modulo_controllers/include/modulo_controllers/RobotControllerInterface.hpp
source/modulo_controllers/src/RobotControllerInterface.cpp

- https://github.com/aica-technology/core/issues/216
Issue raised by @SprGrf. Upon reactivation, controllers have the previous commands buffered for command rate limiting, so we need to reset those in order to avoid unexpected and probably undesired movements upon reactivation.

fix(controllers): reset previous joint commands

---

CHANGELOG.md
source/modulo_controllers/controller_descriptions/modulo_controllers_base_controller_interface.json
source/modulo_controllers/src/BaseControllerInterface.cpp

The controller base class from ROS has two parameters `update_rate` and `is_async`. https://github.com/ros-controls/ros2_control/blob/aefbad38e4371aff499c39f53c8b296a557142cd/controller_interface/src/controller_interface_base.cpp#L37
Because of how our add/set parameter logic works, it is currently not possible to set those parameters on the node because the modulo base class doesn't know about them. By adding them to the internal parameter map, it becomes possible to set them (and not fail validation). For the `is_async` this is all good.
For the `update_rate` it is slightly more annoying because we usually use the name `rate` and type `double` for this. Keeping in mind that I marked both parameters internal, do you want me to investigate further how we could handle this? It would most …

feat(controllers): expose parameters from base class
